"""add new column

Revision ID: 591eaff8536b
Revises: 465bc7c9a7aa
Create Date: 2024-09-15 07:40:20.580036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591eaff8536b'
down_revision: Union[str, None] = '465bc7c9a7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('poster', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_animes_poster'), 'animes', ['poster'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animes_poster'), table_name='animes')
    op.drop_column('animes', 'poster')
    # ### end Alembic commands ###
